#logging:
#  level:
#    root: warn
#    org:
#      springframework:
#        web: debug
#  file:
#    path: E:/log/info.log
spring:
  jackson:
    generator:
      write_numbers_as_strings: true

  # 关闭thymeleaf缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html